language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: satont.js.org
  on:
    branch: master