title: Satont.ru
description: I'm WorldWide

username: Satont WorldWide
user_description: Love code.
user_title: Node.js developer
email: me@satont.ru
github_username:  Satont

google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
